name: Continious Deployment Production

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    name: Setup Node.js and Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 🛠 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🗃 Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.node-version }}-

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 📦 Build Next.js Application
        run: npm run build

  deploy-to-production:
    name: 🚀 Deploy to Production (main branch)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: setup-environment

    steps:
      - name: 🛠 Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PROD_TOKEN }}
        run: |
          npx vercel --token $VERCEL_TOKEN --env NEXT_PUBLIC_ENV=production --prod --yes --confirm
